// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFF67Q1CgHW4x2qRRMAhahxXC4u2auRA',
    appId: '1:221532503028:web:01f85a90002e70efd257a1',
    messagingSenderId: '221532503028',
    projectId: 'first-aid-app-7ae67',
    authDomain: 'first-aid-app-7ae67.firebaseapp.com',
    storageBucket: 'first-aid-app-7ae67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZCbh6OqEzcB6RZPpAxBxvWLIQPYRjLM',
    appId: '1:221532503028:android:140911c1fc76ea3bd257a1',
    messagingSenderId: '221532503028',
    projectId: 'first-aid-app-7ae67',
    storageBucket: 'first-aid-app-7ae67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19WEMAw92sdjhmfE5oJmAggwvaPMYv9s',
    appId: '1:221532503028:ios:c41674203fd304ded257a1',
    messagingSenderId: '221532503028',
    projectId: 'first-aid-app-7ae67',
    storageBucket: 'first-aid-app-7ae67.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstAidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19WEMAw92sdjhmfE5oJmAggwvaPMYv9s',
    appId: '1:221532503028:ios:c41674203fd304ded257a1',
    messagingSenderId: '221532503028',
    projectId: 'first-aid-app-7ae67',
    storageBucket: 'first-aid-app-7ae67.firebasestorage.app',
    iosBundleId: 'com.example.offlineFirstAidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFF67Q1CgHW4x2qRRMAhahxXC4u2auRA',
    appId: '1:221532503028:web:405c62f3445428a8d257a1',
    messagingSenderId: '221532503028',
    projectId: 'first-aid-app-7ae67',
    authDomain: 'first-aid-app-7ae67.firebaseapp.com',
    storageBucket: 'first-aid-app-7ae67.firebasestorage.app',
  );
}
